# Generated by Django 5.1.2 on 2024-10-13 12:16

import datetime
import django.db.models.deletion
import django_countries.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "name",
                    models.CharField(max_length=254, primary_key=True, serialize=False),
                ),
                ("website", models.URLField()),
                ("purpose", models.CharField(max_length=254)),
                ("cost", models.CharField(max_length=254)),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("1", "One time payment"),
                            ("M", "Monthly"),
                            ("Y", "Annually"),
                        ],
                        default="Y",
                        max_length=1,
                        verbose_name="Renewal",
                    ),
                ),
                (
                    "assess_status",
                    models.CharField(
                        choices=[
                            ("N", "New"),
                            ("S", "Submitted"),
                            ("A", "Assessing"),
                            ("R", "Rejected"),
                            ("P", "Approved"),
                            ("E", "Escalated to IPSG"),
                        ],
                        default="N",
                        max_length=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "security_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("N", "No Risk"),
                            ("L", "Low Impact Risk"),
                            ("H", "High Impact Risk"),
                            ("E", "Extreme Risk"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "security_comments",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "privacy_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("N", "No Risk"),
                            ("L", "Low Impact Risk"),
                            ("H", "High Impact Risk"),
                            ("E", "Extreme Risk"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "privacy_comments",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "clinical_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("N", "No Risk"),
                            ("L", "Low Impact Risk"),
                            ("H", "High Impact Risk"),
                            ("E", "Extreme Risk"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "clinical_comments",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("business_owner_approval", models.BooleanField(default=False)),
                (
                    "business_owner_date",
                    models.DateField(blank=True, null=True, verbose_name="Submit Date"),
                ),
                ("attachments", models.FileField(blank=True, null=True, upload_to="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "business_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requestor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("icon_html", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="DHBs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="IPSGmeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TechDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TechInstall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CloudQuestionnaire",
            fields=[
                (
                    "app",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="assessment.application",
                    ),
                ),
                (
                    "disclosure_risk",
                    models.BooleanField(
                        default=False,
                        help_text="The information is publicly available or it can be de-identified so that its release into the public domain would not compromise our obligations to a person or an organisation.",
                        verbose_name="Privacy Breach",
                    ),
                ),
                (
                    "alteration_risk",
                    models.BooleanField(
                        default=False,
                        help_text="No person or organisation will be harmed if the information is altered by mistake or intentionally by a wrongdoer.",
                        verbose_name="Information Alteration",
                    ),
                ),
                (
                    "loss_risk",
                    models.BooleanField(
                        default=False,
                        help_text="No person or orginastion will be harmed if the information is lost by the cloud provider OR we can easily maintain a local copy of the information.",
                        verbose_name="Data Loss",
                    ),
                ),
                (
                    "continuity_risk",
                    models.BooleanField(
                        default=False,
                        help_text="We will be able to carry on our activities if the service is disrupted or is unavailable for an extended.",
                        verbose_name="Business Continuity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ICTRiskAssessment",
            fields=[
                (
                    "app",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="assessment.application",
                    ),
                ),
                (
                    "termsconditions_URL",
                    models.URLField(
                        help_text="1. Please copy and paste the apps terms and conditions from the vendors website. Make sure you get the T&Cs for the version of the app you want."
                    ),
                ),
                (
                    "privacypolicy_URL",
                    models.URLField(
                        help_text="2. Please copy and paste the apps privacy policy from the vendors website. Make sure you get the privacy policy for the version of the app you want."
                    ),
                ),
                (
                    "dhb_record_volume",
                    models.CharField(
                        choices=[
                            ("TENS", "10s"),
                            ("HUNDREDS", "100s"),
                            ("THOUSANDS", "1,000s"),
                            ("TENTHOUSANDS", "10,000s"),
                            ("HUNDREDTHOUSANDS", "100,000s"),
                        ],
                        default="TENS",
                        help_text="3. Provide an estimate of the number of records we expect to store in the application on an annual basis.",
                        max_length=16,
                    ),
                ),
                (
                    "dhb_downtime_before_critical",
                    models.CharField(
                        choices=[
                            ("H", "Hours"),
                            ("D", "Days"),
                            ("M", "Months"),
                            ("I", "Indefinitely"),
                        ],
                        default="H",
                        help_text="4. We can be without this app before our service can no longer function properly. Specify the time interval.",
                        max_length=1,
                    ),
                ),
                (
                    "dhb_log_data_changes",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unsure")],
                        default="U",
                        help_text="5. We will be able to notice if someone accidentally or maliously alters our data stored in the cloud service.",
                        max_length=1,
                    ),
                ),
                (
                    "dhb_small_data_loss",
                    models.CharField(
                        choices=[
                            ("N", "None"),
                            ("I", "Inconvenience"),
                            ("D", "Disruption"),
                            ("P", "Personal Injury"),
                            ("S", "Significant economic loss"),
                            ("H", "Human life endangered"),
                        ],
                        default="N",
                        help_text="6. The effect of someone accidentally or malciously altering a SMALL amount of our data stored in the cloud service.",
                        max_length=1,
                    ),
                ),
                (
                    "dhb_large_data_loss",
                    models.CharField(
                        choices=[
                            ("N", "None"),
                            ("I", "Inconvenience"),
                            ("D", "Disruption"),
                            ("P", "Personal Injury"),
                            ("S", "Significant economic loss"),
                            ("H", "Human life endangered"),
                        ],
                        default="N",
                        help_text="7. The effect of someone accidentally or malciously altering a LARGE amount of our data stored in the cloud service.",
                        max_length=1,
                    ),
                ),
                (
                    "dhb_breach_plan",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unsure")],
                        default="U",
                        help_text="8. We have a plan we can put into effect if we learn that there has been a privacy or security breach concerning our data stored in the cloud service.",
                        max_length=1,
                    ),
                ),
                (
                    "dhb_disrupt_plan",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unsure")],
                        default="U",
                        help_text="9. We have a plan we can put into effect if the cloud service is disrupted for an extended period.",
                        max_length=1,
                    ),
                ),
                (
                    "dhb_perm_loss",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unsure")],
                        default="U",
                        help_text="10. We have a plan we can put into effect if the cloud service loses our data permanently.",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InformationClassification",
            fields=[
                (
                    "app",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="assessment.application",
                    ),
                ),
                (
                    "medical_in_confidence",
                    models.BooleanField(
                        default=False, help_text="Personal health information"
                    ),
                ),
                (
                    "staff_in_confidence",
                    models.BooleanField(
                        default=False,
                        help_text="Identifiable employee and practitioner information that is not intended for the public domain",
                    ),
                ),
                (
                    "commercial_in_confidence",
                    models.BooleanField(
                        default=False,
                        help_text="Commercially sensitive information that needs protection from unauthorised access",
                    ),
                ),
                (
                    "statistical_unclassified",
                    models.BooleanField(
                        default=False,
                        help_text="Statistical or financial information that is non–identifiable",
                    ),
                ),
                (
                    "unclassified",
                    models.BooleanField(
                        default=False, help_text="All other information"
                    ),
                ),
                (
                    "special_handling_sensitive_patient",
                    models.BooleanField(
                        default=False,
                        help_text="Sensitive patient information (eg VIP’s)",
                    ),
                ),
                (
                    "special_handling_sensitive_disease",
                    models.BooleanField(
                        default=False,
                        help_text="Sensitive categories of disease (eg Mental Health)",
                    ),
                ),
                (
                    "special_handling_sensitive_abuse",
                    models.BooleanField(
                        default=False,
                        help_text="Sensitive subjects (violence and abuse; pandemics)",
                    ),
                ),
                (
                    "special_handling_sensitive_other",
                    models.CharField(
                        blank=True, help_text="Other", max_length=200, null=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PrivacyAssessment",
            fields=[
                (
                    "app",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="assessment.application",
                    ),
                ),
                (
                    "desc",
                    models.CharField(
                        blank=True,
                        help_text="Describe your existing systems and the main changes that are proposed. Describe the purpose of the change, including any projected benefits to your organisation or to the individuals affected. Identify the main stakeholders or entities involved, and their role in the project.",
                        max_length=255,
                        null=True,
                        verbose_name="Brief description of the project",
                    ),
                ),
                (
                    "personal_info",
                    models.CharField(
                        blank=True,
                        help_text="A description of the personal information that will be collected, used and/or disclosed; the source of the information; and the purpose of the information for your project.",
                        max_length=255,
                        null=True,
                        verbose_name="Personal information that the project will involve",
                    ),
                ),
                (
                    "substantial_change",
                    models.BooleanField(
                        default=False,
                        help_text="Example: New legislation or policy that makes it compulsory to collect or disclose information",
                        verbose_name="A substantial change to an existing policy, process or system that involves personal information",
                    ),
                ),
                (
                    "risk_register",
                    models.BooleanField(
                        default=False,
                        help_text="Example: Practices or activities listed on your office’s privacy risk register or health and safety register",
                        verbose_name="Any practice or activity that is listed on a risk register kept by your organisation",
                    ),
                ),
                (
                    "collection",
                    models.BooleanField(
                        default=False,
                        help_text="Example: Collecting information about individuals’ location",
                        verbose_name="A new collection of personal information",
                    ),
                ),
                (
                    "new_collect",
                    models.BooleanField(
                        default=False,
                        help_text="Example: Collecting information online rather than on paper forms",
                        verbose_name="A new way of collecting personal information",
                    ),
                ),
                (
                    "new_store",
                    models.BooleanField(
                        default=False,
                        help_text="Example: Storing information in the cloud",
                        verbose_name="A change in the way personal information is stored or secured",
                    ),
                ),
                (
                    "new_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Example: Moving health or financial records to a new database",
                        verbose_name="A change to how sensitive information is managed",
                    ),
                ),
                (
                    "offshore",
                    models.BooleanField(
                        default=False,
                        help_text="Example: Outsourcing the payroll function or storing information in the cloud",
                        verbose_name="Transferring personal information offshore or using a third-party contractor",
                    ),
                ),
                (
                    "disclosure",
                    models.BooleanField(
                        default=False,
                        help_text="Example: Sharing information with other parties in a new way",
                        verbose_name="A new use or disclosure of personal information that is already held",
                    ),
                ),
                (
                    "sharing",
                    models.BooleanField(
                        default=False,
                        help_text="Example: Combining information with other information held on public registers, or sharing information to enable organisations to provide services jointly",
                        verbose_name="Sharing or matching personal information held by different organisations or currently held in different datasets",
                    ),
                ),
                (
                    "policy",
                    models.BooleanField(
                        default=False,
                        help_text="Example: Archiving documents into a facility from which they can’t be easily retrieved",
                        verbose_name="A change in policy that results in people having less access to information that you hold about them",
                    ),
                ),
                (
                    "new_id",
                    models.BooleanField(
                        default=False,
                        help_text="Example: A unique identifier, a biometric, or an online identity system",
                        verbose_name="Establishing a new way of identifying individuals",
                    ),
                ),
                (
                    "monitoring",
                    models.BooleanField(
                        default=False,
                        help_text="Example: Installing a new CCTV system",
                        verbose_name="Surveillance, tracking or monitoring of movements, behaviour or communications",
                    ),
                ),
                (
                    "premises",
                    models.BooleanField(
                        default=False,
                        help_text="Example: Changing the location of the reception desk, meeting rooms  where people may discuss personal details",
                        verbose_name="Changes to your premises that will involve private spaces where clients or customers may disclose their personal information ",
                    ),
                ),
                (
                    "regulatory",
                    models.BooleanField(
                        default=False,
                        help_text="Example: Adding a new medical condition to the requirements of a pilot’s license",
                        verbose_name="New regulatory requirements that could lead to compliance action against individuals on the basis of information about them ",
                    ),
                ),
                (
                    "info_handling",
                    models.CharField(
                        choices=[("H", "High"), ("M", "Medium"), ("L", "Low")],
                        default="L",
                        help_text="Amount of personal information that will be handled.",
                        max_length=1,
                        verbose_name="Level of information handling",
                    ),
                ),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[("H", "High"), ("M", "Medium"), ("L", "Low")],
                        default="L",
                        help_text="Amount of sensitive information that will be handled.",
                        max_length=1,
                        verbose_name="Sensitivity of the information",
                    ),
                ),
                (
                    "significance",
                    models.CharField(
                        choices=[("H", "High"), ("M", "Medium"), ("L", "Low")],
                        default="L",
                        help_text="Magnitude of change.",
                        max_length=1,
                        verbose_name="Significance of the changes",
                    ),
                ),
                (
                    "interaction",
                    models.CharField(
                        choices=[("H", "High"), ("M", "Medium"), ("L", "Low")],
                        default="L",
                        help_text="Number of other organisations involved.",
                        max_length=1,
                        verbose_name="Interaction with others",
                    ),
                ),
                (
                    "public_impact",
                    models.CharField(
                        choices=[("H", "High"), ("M", "Medium"), ("L", "Low")],
                        default="L",
                        help_text="Impact on clients and the wider public. Concerns over aspects of project; or potential for negative media.",
                        max_length=1,
                        verbose_name="Public impact",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="application_type",
            field=models.ManyToManyField(to="assessment.applicationtype"),
        ),
        migrations.CreateModel(
            name="CATmeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meeting_date", models.DateField(default=datetime.date(2024, 10, 14))),
                (
                    "apps_approved",
                    models.ManyToManyField(
                        related_name="approved_apps", to="assessment.application"
                    ),
                ),
                (
                    "apps_escalated",
                    models.ManyToManyField(
                        related_name="escalated_to_IPSG", to="assessment.application"
                    ),
                ),
                (
                    "apps_rejected",
                    models.ManyToManyField(
                        related_name="rejected_apps", to="assessment.application"
                    ),
                ),
                (
                    "attendees",
                    models.ManyToManyField(
                        related_name="attendees", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="CATmeeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assessment.catmeeting",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="dhbs",
            field=models.ManyToManyField(to="assessment.dhbs"),
        ),
        migrations.CreateModel(
            name="HistoricalApplication",
            fields=[
                ("name", models.CharField(db_index=True, max_length=254)),
                ("website", models.URLField()),
                ("purpose", models.CharField(max_length=254)),
                ("cost", models.CharField(max_length=254)),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("1", "One time payment"),
                            ("M", "Monthly"),
                            ("Y", "Annually"),
                        ],
                        default="Y",
                        max_length=1,
                        verbose_name="Renewal",
                    ),
                ),
                (
                    "assess_status",
                    models.CharField(
                        choices=[
                            ("N", "New"),
                            ("S", "Submitted"),
                            ("A", "Assessing"),
                            ("R", "Rejected"),
                            ("P", "Approved"),
                            ("E", "Escalated to IPSG"),
                        ],
                        default="N",
                        max_length=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "security_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("N", "No Risk"),
                            ("L", "Low Impact Risk"),
                            ("H", "High Impact Risk"),
                            ("E", "Extreme Risk"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "security_comments",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "privacy_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("N", "No Risk"),
                            ("L", "Low Impact Risk"),
                            ("H", "High Impact Risk"),
                            ("E", "Extreme Risk"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "privacy_comments",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "clinical_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("N", "No Risk"),
                            ("L", "Low Impact Risk"),
                            ("H", "High Impact Risk"),
                            ("E", "Extreme Risk"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "clinical_comments",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("business_owner_approval", models.BooleanField(default=False)),
                (
                    "business_owner_date",
                    models.DateField(blank=True, null=True, verbose_name="Submit Date"),
                ),
                (
                    "attachments",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "CATmeeting",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="assessment.catmeeting",
                    ),
                ),
                (
                    "business_owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requestor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical application",
                "verbose_name_plural": "historical applications",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInformationClassification",
            fields=[
                (
                    "medical_in_confidence",
                    models.BooleanField(
                        default=False, help_text="Personal health information"
                    ),
                ),
                (
                    "staff_in_confidence",
                    models.BooleanField(
                        default=False,
                        help_text="Identifiable employee and practitioner information that is not intended for the public domain",
                    ),
                ),
                (
                    "commercial_in_confidence",
                    models.BooleanField(
                        default=False,
                        help_text="Commercially sensitive information that needs protection from unauthorised access",
                    ),
                ),
                (
                    "statistical_unclassified",
                    models.BooleanField(
                        default=False,
                        help_text="Statistical or financial information that is non–identifiable",
                    ),
                ),
                (
                    "unclassified",
                    models.BooleanField(
                        default=False, help_text="All other information"
                    ),
                ),
                (
                    "special_handling_sensitive_patient",
                    models.BooleanField(
                        default=False,
                        help_text="Sensitive patient information (eg VIP’s)",
                    ),
                ),
                (
                    "special_handling_sensitive_disease",
                    models.BooleanField(
                        default=False,
                        help_text="Sensitive categories of disease (eg Mental Health)",
                    ),
                ),
                (
                    "special_handling_sensitive_abuse",
                    models.BooleanField(
                        default=False,
                        help_text="Sensitive subjects (violence and abuse; pandemics)",
                    ),
                ),
                (
                    "special_handling_sensitive_other",
                    models.CharField(
                        blank=True, help_text="Other", max_length=200, null=True
                    ),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="assessment.application",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical information classification",
                "verbose_name_plural": "historical information classifications",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ICTVendorAssessment",
            fields=[
                (
                    "app",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="assessment.application",
                    ),
                ),
                (
                    "host_country",
                    django_countries.fields.CountryField(
                        help_text="1. What country or countries is the service hosted in?",
                        max_length=2,
                    ),
                ),
                (
                    "host_service",
                    models.CharField(
                        help_text="2. Name any 3rd party suppliers used by the vendor to supply this service e.g. Microsoft Azure, Amazon Web Services.",
                        max_length=120,
                    ),
                ),
                (
                    "encrypt_transmit",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unsure")],
                        default="U",
                        help_text="5. The data is encrypted when it is being transmitted to the cloud service",
                        max_length=1,
                    ),
                ),
                (
                    "encrypt_stored",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unsure")],
                        default="U",
                        help_text="6. The customer’s data is encrypted inside the cloud service data store",
                        max_length=1,
                    ),
                ),
                (
                    "anonimised",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unsure")],
                        default="U",
                        help_text="7. The data is de-identified BEFORE  it is sent to the cloud service",
                        max_length=1,
                    ),
                ),
                (
                    "back_up",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unsure")],
                        default="U",
                        help_text="8. The vendor backs up the data stored in the cloud service",
                        max_length=1,
                    ),
                ),
                (
                    "extract",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unsure")],
                        default="U",
                        help_text="9. The vendor provides a means for the customer to download a copy of the  data stored  the cloud service",
                        max_length=1,
                    ),
                ),
                (
                    "restore",
                    models.CharField(
                        choices=[
                            ("H", "Hours"),
                            ("D", "Days"),
                            ("M", "Months"),
                            ("N", "Does not"),
                        ],
                        default="U",
                        help_text="10. The vendor undertakes to re-instate the service in the event of an outage in",
                        max_length=1,
                    ),
                ),
                (
                    "log_admin",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unsure")],
                        default="U",
                        help_text="11. The vendor logs sys admin access to  the  data stored in the cloud service",
                        max_length=1,
                    ),
                ),
                (
                    "log_access",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unsure")],
                        default="U",
                        help_text="12. The vendor logs end user access to  the data stored in the cloud service",
                        max_length=1,
                    ),
                ),
                (
                    "shares_data",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unsure")],
                        default="U",
                        help_text="13. The vendor allows 3rd parties to access the data stored in the cloud service",
                        max_length=1,
                    ),
                ),
                (
                    "notify_breach",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unsure")],
                        default="U",
                        help_text="14. The vendor will tell the customer if there has been a security or privacy  incident concerning the data stored in the cloud service",
                        max_length=1,
                    ),
                ),
                (
                    "patches",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unsure")],
                        default="U",
                        help_text="15. The vendor regularly applies  security patches to applications, devices, servers and hypervisors  ",
                        max_length=1,
                    ),
                ),
                (
                    "testing",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unsure")],
                        default="U",
                        help_text="16. The vendor undertakes regular  security testing / certification",
                        max_length=1,
                    ),
                ),
                (
                    "advise_legal_issues",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unsure")],
                        default="U",
                        help_text="17. The vendor will tell the customer if there has been a Court Order concerning the data stored in the cloud service",
                        max_length=1,
                    ),
                ),
                (
                    "ownership",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unsure")],
                        default="U",
                        help_text="18. The vendor’s terms of service give the vendor ownership rights over the data stored in the cloud service",
                        max_length=1,
                    ),
                ),
                (
                    "penalty_breach",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unsure")],
                        default="U",
                        help_text="19. The vendor will pay compensation if the customer suffers a loss as a result of a privacy or security breach of data stored in the cloud service",
                        max_length=1,
                    ),
                ),
                (
                    "penalty_outage",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unsure")],
                        default="U",
                        help_text="20. The vendor will  pay compensation if the  customer suffer a loss as a result of the cloud service being unavailable for any length of time",
                        max_length=1,
                    ),
                ),
                (
                    "report_outages",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unsure")],
                        default="U",
                        help_text="21. The vendor provides a means for the customer to complain in the event of a privacy breach or service disruption",
                        max_length=1,
                    ),
                ),
                (
                    "backgroud_checks",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unsure")],
                        default="U",
                        help_text="22. The vendor’s HR procedures include background vetting of employees and contractors",
                        max_length=1,
                    ),
                ),
                (
                    "devices",
                    models.ManyToManyField(
                        help_text="4. Users access the service using the following technology",
                        to="assessment.techdelivery",
                    ),
                ),
                (
                    "host_deploy",
                    models.ManyToManyField(
                        help_text="3. The service requires the customer to do the following work",
                        to="assessment.techinstall",
                    ),
                ),
            ],
        ),
    ]
