# Generated by Django 5.1.2 on 2024-10-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DHBs",
            new_name="BusinessUnit",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="dhbs",
            new_name="businessunit",
        ),
        migrations.RenameField(
            model_name="ictriskassessment",
            old_name="dhb_breach_plan",
            new_name="bu_breach_plan",
        ),
        migrations.RenameField(
            model_name="ictriskassessment",
            old_name="dhb_disrupt_plan",
            new_name="bu_disrupt_plan",
        ),
        migrations.RenameField(
            model_name="ictriskassessment",
            old_name="dhb_downtime_before_critical",
            new_name="bu_downtime_before_critical",
        ),
        migrations.RenameField(
            model_name="ictriskassessment",
            old_name="dhb_large_data_loss",
            new_name="bu_large_data_loss",
        ),
        migrations.RenameField(
            model_name="ictriskassessment",
            old_name="dhb_log_data_changes",
            new_name="bu_log_data_changes",
        ),
        migrations.RenameField(
            model_name="ictriskassessment",
            old_name="dhb_perm_loss",
            new_name="bu_perm_loss",
        ),
        migrations.RenameField(
            model_name="ictriskassessment",
            old_name="dhb_record_volume",
            new_name="bu_record_volume",
        ),
        migrations.RenameField(
            model_name="ictriskassessment",
            old_name="dhb_small_data_loss",
            new_name="bu_small_data_loss",
        ),
    ]
